# Generated by Django 4.1.7 on 2023-02-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="member",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
